name: Update PR Description with Jira Title
on:
  pull_request:
    types: [opened]

jobs:
  update_pr_description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update PR Description
        run: |
          prNumber="${{ github.event.pull_request.number }}"
          prDescriptionURL="https://api.github.com/repos/${{ github.repository }}/pulls/${prNumber}"
          template="{\"body\": \"Checklist:\n - [ ]  Code follows the coding style guidelines.\n - [ ] Tests have been added or updated.\n - [ ] Documentation has been updated if necessary.\n\n## Sonar Results:\n$sonarUrl\n\n\n## Reference Docs:\n[PR Standards](https://docs.google.com/document/d/1CGi67ib9S-EUmYRmhBLxbc2tLzv0I0C_DXUXnZ-vUkg/edit)\n[PR Review Guideline](https://docs.google.com/document/d/15Wt4jmwLwGkkF1ahCcb_FDKEF6Gbic-yDMbhbXwthRc/edit#)\"}"
          echo "$template" > payload.json
          bearerToken="Bearer ${{ secrets.PAT_TOKEN }}"
          echo "$template" > payload.json

          curl -X PATCH "$prDescriptionURL" \
            -H "Authorization: $bearerToken" \
            -H "Content-Type: application/json" \
            --data-binary "@payload.json"
          
          