name: Update PR Description with Jira Title
on:
  pull_request:
    types: [opened]

jobs:
  update_pr_description:
    runs-on: ubuntu-latest
    # permissions:
    #   pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update PR Description
        run: |
          prNumber="${{ github.event.pull_request.number }}"
          prDescriptionURL="https://api.github.com/repos/${{ github.repository }}/pulls/${prNumber}"
          template="{\"body\": \"Checklist:\n - [ ]  My code follows the style guidelines of this project.\n - [ ] I have performed a self-review of my own code.\n - [ ] I have commented my code, particularly in hard-to-understand areas.\n - [ ] I have made corresponding changes to the documentation.\n - [ ] My changes generate no new warnings.\n - [ ] I have added tests that prove my fix is effective or that my feature works.\n - [ ] New and existing unit tests pass locally with my changes.\n - [ ] Any dependent changes have been merged and published in downstream modules.\n - [ ] I have checked my code and corrected any misspellings.\n\"}"
          echo "$template" > payload.json
          bearerToken="Bearer ${{ secrets.GITHUB_TOKEN }}"
          echo "$template" > payload.json

          curl -X PATCH "$prDescriptionURL" \
            -H "Authorization: $bearerToken" \
            -H "Content-Type: application/json" \
            --data-binary "@payload.json"
          
          